### PR TITLE
docs: add LN and other topics

### PR DESCRIPTION
**Pull request by isaacknjama**

### CODE REVIEW

**Review by BrandonOdiwuor — COMMENTED** [review]
@isaacknjama why can't you add the changes to the `content/2024-08-31-socratic-seminar-10.md` file

**Review by BrandonOdiwuor — COMMENTED** [review]
@isaacknjama I meant update this file 'https://github.com/BitDevsNBO/bitdevsnbo.org/blob/master/content/2024-08-31-socratic-seminar-10.md' which already contains part of the SS10 topics

You should not add a new file just to update part of the original file

**Comment by isaacknjama** [comment]
> @isaacknjama I meant update this file 'https://github.com/BitDevsNBO/bitdevsnbo.org/blob/master/content/2024-08-31-socratic-seminar-10.md' which already contains part of the SS10 topics
> 
> You should not add a new file just to update part of the original file

Should I create a new PR for this? My thought is since it's named the same, it'll save the new version.

**Review by BrandonOdiwuor — APPROVED** [review]
ACK dda8d5561b945c617752d5f8de0b15fa1a9f3eb7

@isaacknjama I have rebased the PR and now it's OK

**Comment by munjesi** [comment]
@isaacknjama image

**Pull request merged**
